[APM] Add missing `IntlProvider` to unit test (#150137)
Jest tests in APM are currently failing with:

```
Error: Uncaught [Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry. Using default message as fallback.]
```

Adding the `IntlProvider` fixes the problem